### ISSUE TITLE
Swift Compiler Error (Swift 4.2)

### ISSUE THREAD

**Issue by warpling** [dagostini/BBPortal#2]
"Overlapping accesses to 'error', but modification requires exclusive access; consider copying to a local variable"

Seems related to passing error to `onCompleted` when error might not be initialized yet? Seems related to these compiler changes:
* https://forums.swift.org/t/upgrading-exclusive-access-warning-to-be-an-error-in-swift-4-2/12704/6
* https://bugs.swift.org/browse/SR-8063

```
                var error: NSError?
                self?.coordinator?.coordinate(writingItemAt: url, options: .forReplacing, error: &error, byAccessor: { (url) in
                    
                    let dictToSave: [String: Any?] = [DictKey.sender.rawValue: self?.objectID,
                                                      DictKey.payload.rawValue: data]
                    
                    let dictData = NSKeyedArchiver.archivedData(withRootObject: dictToSave)
                    try? dictData.write(to: url)
                    
                    onCompleted?(error)
                })
```

(Super interesting and cool library btw!)

**Comment by dagostini** [comment]
Thanks :) It was great fun to write it.

Didn't even know people are using this :) I'll try and fix it, but I have so many things going on that it might take a while :(

**Comment by warpling** [comment]
I was hoping to try it out for a new Blackbox puzzle ;) I think it’s a one line fix. I “fixed” it by removing the error passing but wasn’t sure of the more correct solution; if you read the method header I think the error handling is a little more counterintuitive than how it’s currently implemented.

**Comment by dagostini** [comment]
You're right, it's a bit weird. The error shouldn't be used in that completion block. You can return nil in that onCompleted and outside of the scope of the block do an if-let and return the error. Other than that, I can't think of a better way at the moment :)

That's awesome about the puzzle, send me a link to the app when it's finished, will ya :)

**Comment by warpling** [comment]
It seemed like that was the suggested way of handling it? Will keep an eye out for the new pod version! App and the puzzle using it (2 red squares in the “Erudite Pack”) is already live but I’m using this to tweak how it’s solved 🙃

**Comment by dagostini** [comment]
You work on blackbox! That's awesome! Congrats on winning the design award!
Just letting you know, the new pod version is out. Let me know if it works so I can close the issue.

**Comment by warpling** [comment]
Just downloaded and tested it – works great :)

Keep an eye out for an update. One of the two red puzzles in the Erudite pack will be doing something clever with BBPortal. Should be in the credits too…
